# Visit https://golangci-lint.run/ for usage documentation
# and information on other useful linters
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-dirs:
    - ./tools  # not really source code (tools.go pattern?)

run:
  modules-download-mode: mod
  timeout: 10m

linters:
  disable-all: true
  enable:
    - durationcheck
    - errcheck
    #  - copyloopvar   # was exportloopref before, copyloopvar needs go 1.22
    #  - forcetypeassert
    #  - godot
    #  - gofmt
    - gosimple
    - ineffassign
    - makezero
    - misspell
    - nilerr
    - predeclared
    - staticcheck
    - tenv
    - unconvert
    - unparam
    - unused
    - govet # vet got renamed
