on: 
  workflow_dispatch:
    inputs:
      snapshot:  # note: snapshot builds are not actually published
        required: false
        type: boolean
        default: false
      verbose:
        required: false
        type: boolean
        default: false  

jobs:
  test:
    name: "Manual Release"
    uses: ./.github/workflows/release.yml
    with: 
      snapshot: ${{ inputs.snapshot }}
      verbose: ${{ inputs.verbose }}